### ISSUE TITLE
How to proceed further?

### ISSUE THREAD

**Issue by omkarpatil18** [pangfumin/ACG-localizer#2]
Hi! 
This is not an issue, but I'm new at this and it'll be of great help if you could tell me what I should do after building this image. I want to run the ACG localizer to get camera pose estimates for Shop Facade dataset. How do I go about compiling ACG localizer on the image? I know the commands, but am not very familiar with docker.

Thank you,
Omkar

**Comment by seungjuuuuuu** [comment]
> Hi! This is not an issue, but I'm new at this and it'll be of great help if you could tell me what I should do after building this image. I want to run the ACG localizer to get camera pose estimates for Shop Facade dataset. How do I go about compiling ACG localizer on the image? I know the commands, but am not very familiar with docker.
> 
> Thank you, Omkar

Hi! Have you solved this problem?

**Comment by omkarpatil18** [comment]
Hi! Nope, I left this long ago sorry.
